version: '2'
services:
  # Polis PostgreSQL Database
  polisdb:
    build: uzzal2k5/polis_postgresql:1.0
    container_name: polisdb
    ports:
      - "5432:5432/tcp"
    restart: on-failure

  # Polis Server
  polisserver:
    build: polisserver
    container_name: polisserver
    ports:
      - "5000:5000/tcp"
    links:
      - polisdb
    environment:
      DATABASE_URL: postgres://polis:polis@polisdb/polis
      STATIC_FILES_HOST: clientadmin
    restart: on-failure

  # Polis Client Admin & Participants
  clientparticipant:
    build: polisClientParticipation
    container_name: clientparticipant
    hostname: clientparticipant
    environment:
      SERVICE_URL: polisserver
    links:
      - polisserver
    ports:
      - "5001:5001"
      - "8000:8000"
    restart: on-failure

  # Polis Client Admin
  clientadmin:
    build: polisClientAdmin
    container_name: clientadmin
    hostname: clientadmin
    environment:
      SERVICE_URL: polisserver
    links:
      - polisserver
    ports:
      - "5002:5002"
    restart: on-failure

  # Polis Math Container
  math:
    build: polismath
    container_name: math
    hostname: math
    environment:
      SERVICE_URL: polisserver
      DATABASE_URL: postgres://polis:polis@polisdb/polis
    links:
      - polisserver
      - polisdb
    ports:
      - "8080:8080"
    restart: on-failure



